---
- name: configure weather-app VM
  hosts: default
  become: yes
  remote_user: yes

  tasks:
  - name: disable selinux
    ansible.posix.selinux:
      state: disabled
  - name: add source files
    copy:
      src: '{{ playbook_dir }}/src/'
      dest: /home/vagrant/weather-app/
  - name: add docker-ce repo
    copy:
      src: '{{ playbook_dir }}/docker-ce.repo'
      dest: /etc/yum.repos.d/
    loop:
  - name: install dependencies
    yum:
      name: '{{ item }}'
      state: latest
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - conntrack-tools
  - name: start and enable docker
    systemd:
      name: docker
      state: restarted
      enabled: yes
  - name: add daemon.json with syslog driver
    copy:
      dest: /etc/docker/daemon.json
      content: |
        {
          "log-driver": "syslog"
        }
  - name: restart docker
    systemd:
      name: docker
      state: restarted
      enabled: yes
  - name: enable masquerade
    ansible.posix.firewalld:
      zone: public
      masquerade: yes
      permanent: yes
      state: enabled
  - name: reload firewalld
    systemd:
      name: firewalld
      state: restarted
...
